In [11]:
"""
1. Use Cryptocompare to get BTC info
2. Use Robinhood stocks to trade BTC
3. Train ML model to predict up in 5, 10, 15 mins
4. 

"""
import sys
sys.path.append('../')

import cryptocompare
import pandas as pd
import numpy as np
import time
import robin_stocks.robinhood as rh
from config.rh.config import USERNAME, PASSWORD
from config.cryptocompare.config import KEY


login = rh.login(USERNAME, PASSWORD)

In [12]:
# rh.get_all_open_crypto_orders()
# rh.order_buy_crypto_by_price('BTC',500)
# #Buy 10 shares of Apple at market price
# rh.order_buy_market('AAPL',10)
# #Sell half a Bitcoin is price reaches 10,000
# rh.order_sell_crypto_limit('BTC',0.5,10000)
# #Buy $500 worth of Bitcoin
# rh.order_buy_crypto_by_price('BTC',500)
# #Buy 5 $150 May 1st, 2020 SPY puts if the price per contract is $1.00. Good until cancelled.
# rh.order_buy_option_limit('open','debit',1.00,'SPY',5,'2020-05-01',150,'put','gtc')
# rh.get_latest_price('AAPL')

data = rh.get_crypto_historicals('BTC', '5minute', 'day')
pd.DataFrame(data)

,begins_at,open_price,close_price,high_price,low_price,volume,session,interpolated,symbol
0,2021-12-29T19:05:00Z,47510.315000,47388.975000,47565.222293,47343.894649,0,reg,False,BTCUSD
1,2021-12-29T19:10:00Z,47388.975000,47359.315000,47492.247968,47318.921893,0,reg,False,BTCUSD
2,2021-12-29T19:15:00Z,47359.315000,47375.335000,47376.555976,47279.900107,0,reg,False,BTCUSD
3,2021-12-29T19:20:00Z,47375.335000,47399.495000,47442.341918,47340.037668,0,reg,False,BTCUSD
4,2021-12-29T19:25:00Z,47399.495000,47427.955000,47463.902313,47341.168380,0,reg,False,BTCUSD
...,...,...,...,...,...,...,...,...,...
283,2021-12-30T18:40:00Z,47617.900000,47635.225000,47656.220545,47568.998497,0,reg,False,BTCUSD
284,2021-12-30T18:45:00Z,47635.225000,47686.570000,47706.704344,47567.575450,0,reg,False,BTCUSD
285,2021-12-30T18:50:00Z,47686.570000,47839.315000,47908.690000,47640.175762,0,reg,False,BTCUSD
286,2021-12-30T18:55:00Z,47839.315000,47881.015000,47916.716755,47788.454164,0,reg,False,BTCUSD
287,2021-12-30T19:00:00Z,47881.015000,47847.905000,47897.635632,47790.210698,0,reg,False,BTCUSD

In [13]:
cryptocompare.cryptocompare._set_api_key_parameter(KEY)

'&api_key=6631c11f19135c0803f8ec9f00a6a7199631a43c114f92d25ea5c75104497ed6'

In [14]:
cryptocompare.get_price('BTC',currency='USD')

{'BTC': {'USD': 47799.17}}

In [8]:
# cryptocompare.get_historical_price_minute('BTC', 'EUR', limit=24, exchange='CCCAGG', toTs=datetime.datetime.now())
btc = pd.DataFrame(cryptocompare.get_historical_price_minute('BTC', currency='USD', limit=1440))

In [9]:
btc['time'] = pd.to_datetime(btc['time'],unit='s')
btc

,time,high,low,open,volumefrom,volumeto,close,conversionType,conversionSymbol
0,2021-12-29 19:00:00,47551.69,47536.06,47539.16,9.002,427928.72,47550.52,direct,
1,2021-12-29 19:01:00,47555.42,47541.92,47550.52,5.019,238660.21,47542.77,direct,
2,2021-12-29 19:02:00,47555.50,47541.17,47542.77,2.595,123364.65,47547.68,direct,
3,2021-12-29 19:03:00,47551.09,47497.39,47547.68,18.620,884738.85,47497.39,direct,
4,2021-12-29 19:04:00,47533.32,47488.45,47497.39,10.530,500237.85,47518.39,direct,
...,...,...,...,...,...,...,...,...,...
1436,2021-12-30 18:56:00,47875.12,47827.66,47867.81,45.790,2190708.49,47857.43,direct,
1437,2021-12-30 18:57:00,47896.84,47857.38,47857.43,27.320,1308110.95,47887.05,direct,
1438,2021-12-30 18:58:00,47897.24,47867.32,47887.05,55.470,2656022.48,47891.94,direct,
1439,2021-12-30 18:59:00,47898.69,47853.22,47891.94,44.570,2134019.32,47882.59,direct,
1440,2021-12-30 19:00:00,47887.96,47882.59,47882.59,0.000,0.00,47887.96,direct,